### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by AlexMaximilian** [daluisgarcia/flask-project-example#1]
ImportError: cannot import name 'escape' from 'jinja2' (/Users/alex/Library/Python/3.10/lib/python/site-packages/jinja2/__init__.py)

**Comment by daluisgarcia** [comment]
Hello! This error might be happening because you have an old version of flask package, as it is said in this thread: https://stackoverflow.com/a/71735103
I have added a README.md file with some instructions. I recommend you to create a virtual environment with the command "python -m venv venv", activate it using ". venv/scripts/activate" and then follow the installation steps in the README file.
Thank you for the comment.
